### ISSUE TITLE
Split out parse_features logic into an importable library

### ISSUE THREAD

**Issue by mxmxchere** [gardenlinux/gl-oci#26]
The builder has the [parse_features](https://github.com/gardenlinux/builder/blob/main/builder/parse_features) tool. It  provides core functionality that we need for the gl-oci project as well. Therefore, we should extract the core functionality (parse the features-folder and provide a query interface to retrieve, resolved dependecies) of the tool [to its own GitHub repository](https://github.com/gardenlinux/parse_features_lib) and make it available as a library.
parse_features in gl/builder will remain at its current place but will facilitate the library that has been split out. The tool's behaviour must not change.

Inclusion method into gl/builder/parse_features: to be determined: git clone, wget+checksum, apt packaging, pypi,...
Inclusion method for gl-oci: `git+` syntax

**Comment by mxmxchere** [comment]
We now have a state that is usable in https://github.com/gardenlinux/parse_features_lib The two core functions of parse_features have been split out, no change to the logic. So it should not cause any issues to include the functions from `parse_features_lib`. We also tried to use those two functions in an external program which worked. An example can be found in the README.

**Comment by Vincinator** [comment]
https://github.com/gardenlinux/python-gardenlinux-lib
