### ISSUE TITLE
Get up to speed on the existing work

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gl-oci#33]
Task one is to read carefully the existing docs:
OCI Initial Delivery[#32](https://github.com/gardenlinux/python-gardenlinux-cli/issues/17)
[RFD OCI Implementation Specification](https://github.com/gardenlinux/RFD/blob/0012/docs/rfd-12.md)

**Comment by mxmxchere** [comment]
The current open ends are:
* Integration of the `glcli oci` tool into the build pipeline https://github.com/gardenlinux/gardenlinux/pull/2292 https://github.com/gardenlinux/gardenlinux/issues/2441
* Refining of the behavior of the `glcli oci` tool, I have the feeling that it needs a bit of polishing still (tests, edgecases)
